[package]
name = "FlightDist"
version = "1.4.7"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
geoutils = "0.5.1"
colored = "3.0.0"
csv = "1.4.0"
dialoguer = { version = "0.12.0", features = ["history"] }
unidecode = "0.3.0"

[[bin]]
name = "FlightDist"
path = "main.rs"